language: python
python:
    # - 3.6
    # - 3.7
    # - 3.8
    - 3.9
    # - pypy3
before_install:
    - sudo apt-get -y install libmpc-dev
install:
    - git clone https://github.com/lschoe/mpyc
    - cd mpyc
    - python setup.py install
    - pip install gmpy2
    - cd ..
    - git clone https://github.com/toonsegers/sec_groups/
    - cd sec_groups
    - python setup.py install
    - cd ..
script: python -m unittest discover